menu:
  首页: /
  Python: /tags/Python
  IOS: /tags/IOS
  归档: /archives

excerpt_link: Read More
archive_yearly: false

widgets:
  - category
  - tag
  - tagcloud
  - recent_posts
  - blogroll

blogrolls:
  - Heroic Yang's Blog: http://heroicyang.com/

fancybox: true

duoshuo_shortname: 

google_analytics:
rss:
